# Makefile for compiling LaTeX and running the question database script

# Define the main output and input files
TEX_FILE = generated_latex_document.tex
PDF_FILE = generated_latex_document.pdf
SCRIPT_FILE = generate_handouts.py
SNIPPETS = $(wildcard snippets/*.tex)

# Define the default target for the Makefile
all: $(PDF_FILE)

# Rule to generate the LaTeX file by running the Python script
$(TEX_FILE): $(SCRIPT_FILE) QuestionDatabase.py question_database.csv $(SNIPPETS)
	python3 $(SCRIPT_FILE)

# Rule to compile the LaTeX file into a PDF
$(PDF_FILE): $(TEX_FILE)
	pdflatex $(TEX_FILE)

# Clean up auxiliary files generated by LaTeX compilation
clean:
	rm -f *.aux *.log

# Full clean: remove generated files, including the PDF and the LaTeX file
distclean: clean
	rm -f $(PDF_FILE) $(TEX_FILE)

# Run this target if only the Python script or snippets are modified
handout: $(SCRIPT_FILE) $(SNIPPETS)
	python3 $(SCRIPT_FILE)

.PHONY: all clean distclean handout

